name: reproduce-and-artifacts

on:
  workflow_dispatch:
    inputs:
      num_obs:
        description: "number of observations"
        required: true
        default: "40"
      grid:
        description: "grid size"
        required: true
        default: "80"
      noise:
        description: "observation noise"
        required: true
        default: "0.1"
      vx:
        description: "flow vx"
        required: true
        default: "1.0"
      vy:
        description: "flow vy"
        required: true
        default: "0.3"
      seed:
        description: "random seed"
        required: true
        default: "7"
      commit_artifacts:
        description: "commit artifacts back to repo"
        required: true
        default: "false"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python scripts/generate_synth.py --n_obs ${{ github.event.inputs.num_obs }} --grid ${{ github.event.inputs.grid }} --noise ${{ github.event.inputs.noise }} --vx ${{ github.event.inputs.vx }} --vy ${{ github.event.inputs.vy }} --seed ${{ github.event.inputs.seed }}
          python scripts/run_baseline.py

      - name: Commit artifacts back to repo
        if: ${{ github.event.inputs.commit_artifacts == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.csv figures/*.png
          git commit -m "chore: add artifacts from workflow run"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
