name: reproduce-minimal

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: |
          python scripts/generate_synth.py --n_obs 20 --grid 40 --noise 0.1 --vx 1.0 --vy 0.3 --seed 42
          python scripts/run_baseline.py --length_parallel 30 --length_cross 8 --alpha 1e-6 --fast_loo
      - uses: actions/upload-artifact@v4
        with:
          name: minimal-results
          path: |
            data/*
            figures/*
