name: reproduce-and-sweep

on:
  workflow_dispatch:
    inputs:
      n_obs:   { description: "number of observations", default: "40" }
      grid:    { description: "grid size",              default: "80" }
      noise:   { description: "observation noise",      default: "0.1" }
      vx:      { description: "flow velocity x",        default: "1.0" }
      vy:      { description: "flow velocity y",        default: "0.3" }
      seed:    { description: "random seed",            default: "7" }
      commit_artifacts:
        description: "commit artifacts back to repo"
        default: "false"

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r requirements.txt

  sweep-baseline:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lp: [20, 30, 40]
        lc: [6, 8, 12]
    steps:
      - uses: actions/checkout@v4
      - name: Run sweep baseline
        run: |
          for i in 1 2 3; do
            echo "::group::Attempt $i"
            if python scripts/run_baseline.py \
              --length_parallel ${{ matrix.lp }} \
              --length_cross ${{ matrix.lc }} \
              --alpha 1e-6 --no_opt; then
              echo "::endgroup::"
              break
            else
              echo "::warning:: Attempt $i failed, retrying..."
              echo "::endgroup::"
              sleep 5
            fi
          done
      - uses: actions/upload-artifact@v3
        with:
          name: baseline-${{ matrix.lp }}-${{ matrix.lc }}
          path: figures/

  physics-soft:
    needs: setup-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run physics soft constraint
        run: |
          python scripts/run_physics_soft.py \
            --length_parallel_list 20 30 40 \
            --length_cross_list 6 8 12 \
            --lambda_phys 1.0 --kappa 1.0
      - uses: actions/upload-artifact@v3
        with:
          name: physics-soft
          path: figures/

  aggregate:
    needs: [sweep-baseline, physics-soft]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
      - name: Merge metrics + generate heatmap
        run: |
          python scripts/make_fourpanel.py
      - uses: actions/upload-artifact@v3
        with:
          name: all-results
          path: figures/

      - name: Commit artifacts back
        if: ${{ github.event.inputs.commit_artifacts == 'true' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add figures/ data/
          git commit -m "add artifacts [ci skip]" || echo "No changes"
          git push
